SELECT * FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
UNION
SELECT * FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO; 

SELECT * FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;